### ISSUE TITLE
Documentación parte 1 

### ISSUE THREAD

**Issue by Ximena1998** [Ximena1998/ExamenIngenieriaRequisitos#3]
- [x] Visión 
- [x] Restricciones tecnológicas de la solución 
- [x] Listar y detallar las de fuentes de requerimientos

**Comment by leninsanchez** [comment]
**VISIONAMIENTO**

Para los clientes de una institución financiera más importante del país, el sistema AHORRA+ es una aplicación web y móvil, que permite a los clientes  organizar sus finanzas para fomentar el ahorro programado en la Institución, teniendo la capacidad de permitir a los clientes que a partir de sus ingresos y egresos programen metas de ahorro mensual y anual, a diferencia de otras aplicaciones como (Fintonic, Mooverang, Monefy, Mint), nuestro sistema permite al usuario controlar sus gastos mensualmente y anualmente, ayudando así a los clientes a un mejor ahorro en consumos aumentando así su capital y economía mediante notificaciones, además incluye (Parametrización de las cuentas, simulaciones, control y seguimiento de gastos e ingresos, consultas).
